pipeline {
    agent any

    environment {
        COMPOSE_DIR = 'docker'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Stop Old Containers') {
            steps {
                sh '''
                docker rm -f telemedicine_backend telemedicine_frontend telemedicine_nginx telemedicine_db || true
                '''
            }
        }

        stage('Build Images') {
            steps {
                dir("${COMPOSE_DIR}") {
                    sh '''
                    docker compose build
                    '''
                }
            }
        }

        stage('Start Containers') {
            steps {
                dir("${COMPOSE_DIR}") {
                    sh '''
                    docker compose up -d
                    '''
                }
            }
        }

        stage('Verify Containers') {
            steps {
                sh '''
                docker ps
                '''
            }
        }
    }

    post {
        success {
            echo "Deployment completed successfully 🚀"
        }
        failure {
            echo "Pipeline failed ❌"
        }
    }
}