pipeline {
    agent any

    environment {
        DOCKERHUB = "ahmed7amed9"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }

        stage('Build Images') {
            steps {
                sh '''
                docker build -t $DOCKERHUB/telemedicine-backend ./backend
                docker build -t $DOCKERHUB/telemedicine-frontend ./frontend
                docker build -t $DOCKERHUB/telemedicine-nginx ./nginx
                '''
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                docker push $DOCKERHUB/telemedicine-backend
                docker push $DOCKERHUB/telemedicine-frontend
                docker push $DOCKERHUB/telemedicine-nginx
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f kubernetes/deployments/
                kubectl apply -f kubernetes/services/
                '''
            }
        }

        stage('Verify') {
            steps {
                sh 'kubectl get pods'
                sh 'kubectl get svc'
            }
        }
    }

    post {
        success {
            echo "CI/CD Pipeline Completed 🚀"
        }
        failure {
            echo "Pipeline Failed ❌"
        }
    }
}