apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ahmed7amed9/telemedicine-backend:latest
        imagePullPolicy: Always

        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: telemedicine
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres

        ports:
        - containerPort: 8000