apiVersion: v1
kind: Service
metadata:
  name: backend-service # Changed back to match Nginx!
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000      # Nginx tries to connect to port 5000
      targetPort: 5000  # The pod is now running on 8000, so we cleanly map 5000 to 8000!